default['sonar']['web_domain'] = "metrics.typo3.org"
default['sonar']['web_host']   = "127.0.0.1"
default['sonar']['web_port']   = "9001"
default['sonar']['jdbc_url']               = "jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8"
default['sonar']['jdbc_driverClassName']   = "com.mysql.jdbc.Driver"
default['sonar']['jdbc_validationQuery']   = "select 1"